WHITESPACE = _{ " " | "\n" }
COMMENT    = _{ "#" ~ (!NEWLINE ~ ANY)* }

// simple atoms
alpha         =  { 'a'..'z' | 'A'..'Z' }
digit         =  { '0'..'9' }
identifier    = @{ (alpha | "_") ~ (alpha | digit | "_")* }
number        = @{ digit+ }
string_char   =  { !("\"" | "\\") ~ ANY | "\\" ~ ("n" | "t" | "r" | "\"" | "\\") }
string_literal = @{ "\"" ~ string_char* ~ "\"" }

primary = {
    conditional
  | function_call
  | number
  | string_literal
  | identifier
  | function_definition
  | block
}

expression = { comparison ~ ((add_op | sub_op) ~ comparison)* }
comparison = { term ~ ((eq_op | ne_op | le_op | lt_op | ge_op | gt_op) ~ term)? }
term = { factor ~ ((mul_op | div_op) ~ factor)* }
factor = { primary }

add_op = { "+" }
sub_op = { "-" }
mul_op = { "*" }
div_op = { "/" }
eq_op = { "==" }
ne_op = { "!=" }
lt_op = { "<" }
le_op = { "<=" }
gt_op = { ">" }
ge_op = { ">=" }

function_arguments = { expression ~ ("," ~ expression)* }
function_call      = { identifier ~ "(" ~ function_arguments ~ ")" }

conditional = { "if" ~ expression ~ "then" ~ expression ~ "else" ~ expression }

block = { "(" ~ assignment* ~ expression ~ ")" }

ident_list          = { identifier ~ ("," ~ identifier)* }
function_definition = { "|" ~ ident_list? ~ "|" ~ expression }

assignment = { identifier ~ "=" ~ expression }

program = _{ SOI ~ (assignment)* ~ EOI }

